// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel Particle
#pragma kernel Density
#pragma kernel Pressure

#pragma kernel RandomInit
#pragma kernel Step

#define X 1024
#define PI 3.14159265359f

/*
    ################################
    ########### STRUCTS ############
    ################################
*/

#define IndexRes 10
#define BucketSize 100

struct Block
{
    uint bucket[BucketSize + 1]; // Last is for count
};

struct BlockIndex
{
    Block blocks[IndexRes][IndexRes][IndexRes];
};

/*
    ################################
    ############ DATA ##############
    ################################
*/

float scale;
float2 offset;

int numParticles;
float particleRadius;
float particleMass;
float restitutionCoeff;
float targetDensity;
float pressureCoeff;
float kernelRadius;
float kernelRadius2;
float kernelRadius3;
float kernelRadius4;
float kernelRadius5;

RWStructuredBuffer<float2> positions;
RWStructuredBuffer<float2> velocities;
RWStructuredBuffer<float2> forces;
RWStructuredBuffer<float> densities;

RWStructuredBuffer<BlockIndex> blockIndex;
RWStructuredBuffer<uint> reverseIndex;

RWTexture2D<float4> result;

RWStructuredBuffer<int> stats;

float deltaTime;

/*
    ################################
    ###### PARTICLE KERNELS ########
    ################################
*/

struct Spiky
{
    float F(float dist)
    {
        if (dist >= kernelRadius)
        {
            return 0.0f;
        }
        
        float x = 1.0f - dist / kernelRadius;
        return 15.0f / (PI * kernelRadius3) * x * x * x;
    }
    
    float dF(float dist)
    {
        if (dist >= kernelRadius)
        {
            return 0;
        }

        float x = 1.0f - dist / kernelRadius;
        return -45.0f / (PI * kernelRadius4) * x * x;
    }
    
    float ddF(float dist)
    {
        if (dist >= kernelRadius)
        {
            return 0;
        }

        float x = 1.0f - dist / kernelRadius;
        return 90.0f / (PI * kernelRadius5) * x;
    }
    
    float grad(float dist, float2 normalizedDirToCenter)
    {
        return -dF(dist) * normalizedDirToCenter;
    }
};

Spiky SpikyParticleKernel;

/*
    ################################
    ############ UTIL ##############
    ################################
*/

float2 rand(float2 p)
{
    float3 p3 = frac(float3(p.xyx) * float3(.1031, .1030, .0973));
    p3 += dot(p3, p3.yzx + 33.33);
    return frac((p3.xx + p3.yz) * p3.zy);
}

float2 transform(float2 x)
{
    return (x + offset) * scale;
}

float magnitude2(float2 a)
{
    return dot(a, a);
}

/*
    ################################
    ############# SIM ##############
    ################################
*/

void resolveCollisions(uint i)
{
    float halfBound = 0.5f - particleRadius;
    float2 pos = positions[i];
    float2 vel = velocities[i];
    
    if (abs(pos.x) > halfBound)
    {
        pos.x = halfBound * sign(pos.x);
        vel.x *= -1 * restitutionCoeff;
    }
    if (abs(pos.y) > halfBound)
    {
        pos.y = halfBound * sign(pos.y);
        vel.y *= -1 * restitutionCoeff;
    }
 
    positions[i] = pos;
    velocities[i] = vel;
}

float sampleKernelAt(float2 pos)
{
    float sum = 0.0f;
    
    for (int i = 0; i < numParticles; i++)
    {
        sum += SpikyParticleKernel.F(distance(pos, positions[i]));
    }
    
    return sum;
}

void computeDensities(uint i)
{
    densities[i] = particleMass * sampleKernelAt(positions[i]);
    InterlockedMax(stats[0], (int) (densities[i] * 1000));
}

float getPressureFromDensity(float density)
{
    float diff = density - targetDensity;
    return pressureCoeff * diff;
}

void computePressures(int i)
{

}

void preStep(uint i)
{
    // Reset forces
    forces[i] = 0.0f;
    
    // Update index
    
    // Recalculate neighbors
    
    // Compute densities
    computeDensities(i);
    
    // Compute pressures
    computePressures(i);
}

/*
    ################################
    ############ KERN ##############
    ################################
*/

[numthreads(X,1,1)]
void Particle(uint3 id : SV_DispatchThreadID)
{
    uint w, h;
    result.GetDimensions(w, h);
    uint total = w * h;
    
    if (id.x >= total)
        return;
    
    uint2 coords = uint2(id.x / h, id.x % h);
    float2 ncoords = float2((float) coords.x / w, (float) coords.y / h);
    float2 tcoords = transform(ncoords);
    
    for (int i = 0; i < numParticles; i++)
    {
        if (distance(tcoords, positions[i]) < particleRadius)
        {
            result[coords.xy] = float4(1.0f, 1.0f, 1.0f, 1.0f);
            return;
        }
    }

    result[coords.xy] = float4(0.0f, 0.0f, 0.0f, 1.0f);
}

[numthreads(X, 1, 1)]
void Density(uint3 id : SV_DispatchThreadID)
{
    uint w, h;
    result.GetDimensions(w, h);
    uint total = w * h;
    
    if (id.x >= total)
        return;
    
    uint2 coords = uint2(id.x / h, id.x % h);
    float2 ncoords = float2((float) coords.x / w, (float) coords.y / h);
    float2 tcoords = transform(ncoords);
    
    float density = particleMass * sampleKernelAt(tcoords);
    InterlockedMax(stats[0], (int) (density * 1000));
    
    result[coords.xy] = float4(density, density, 0.0f, 1.0f);
}

[numthreads(X, 1, 1)]
void Pressure(uint3 id : SV_DispatchThreadID)
{
    uint w, h;
    result.GetDimensions(w, h);
    uint total = w * h;
    
    if (id.x >= total)
        return;
    
    uint2 coords = uint2(id.x / h, id.x % h);
    float2 ncoords = float2((float) coords.x / w, (float) coords.y / h);
    float2 tcoords = transform(ncoords);
    
    float density = particleMass * sampleKernelAt(tcoords);
    float pressure = getPressureFromDensity(density);
    
    InterlockedMin(stats[1], (int) (pressure * 1000));
    InterlockedMax(stats[2], (int) (pressure * 1000));
    
    
    float4 neg = float4(1.0f, 0.0f, 0.0f, 1.0f);
    float4 zero = float4(1.0f, 1.0f, 1.0f, 1.0f);
    float4 pos = float4(0.0f, 0.0f, 1.0f, 1.0f);
    
    result[coords.xy] = pressure < 0.0f ? smoothstep(zero, neg, -pressure) : smoothstep(zero, pos, pressure);
}


[numthreads(X, 1, 1)]
void RandomInit(uint3 id : SV_DispatchThreadID)
{
    uint x, _;
    positions.GetDimensions(x, _);

    if (id.x >= x)
        return;
    
    positions[id.x] = transform(rand(id.xx));
    velocities[id.x] = (float2)0;
    forces[id.x] = (float2)0;
}

[numthreads(X, 1, 1)]
void Step(uint3 id : SV_DispatchThreadID)
{
    uint x, _;
    positions.GetDimensions(x, _);

    if (id.x >= x)
        return;
    
    preStep(id.x);
    
    velocities[id.x] += float2(0, -9.81)  * deltaTime;
    positions[id.x] += velocities[id.x] * deltaTime;
    
    resolveCollisions(id.x);
}