// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel Particle
#pragma kernel Density
#pragma kernel Pressure

#pragma kernel RandomInit
#pragma kernel Step
#pragma kernel PreStep

#define X 1024
#define PI 3.14159265359f

/*
    ################################
    ########### STRUCTS ############
    ################################
*/

#define IndexRes 10
#define BucketSize 100

struct Block
{
    uint bucket[BucketSize + 1]; // Last is for count
};

struct BlockIndex
{
    Block blocks[IndexRes][IndexRes][IndexRes];
};

/*
    ################################
    ############ DATA ##############
    ################################
*/

float scale;
float2 offset;

bool pointerActive = 0;
float pointerRadius = 0.3f;
float pointerStrength = 1.0f;
float2 pointerPos = float2(-10000, -10000);

int numParticles;
float particleRadius;
float particleMass;
float restitutionCoeff;
float targetDensity;
float pressureCoeff;
float viscosityCoeff;
float gravityCoeff;
float kernelRadius;
float kernelRadius2;
float kernelRadius3;
float kernelRadius4;
float kernelRadius5;

RWStructuredBuffer<float2> positions;
RWStructuredBuffer<float2> predictedPositions;
RWStructuredBuffer<float2> velocities;
RWStructuredBuffer<float2> forces;
RWStructuredBuffer<float> densities;

RWStructuredBuffer<BlockIndex> blockIndex;
RWStructuredBuffer<uint> reverseIndex;

RWTexture2D<float4> result;

RWStructuredBuffer<int> stats;

float deltaTime;
static float fixedDeltaTime = 0.005f;

/*
    ################################
    ###### PARTICLE KERNELS ########
    ################################
*/

struct Spiky
{
    float F(float dist)
    {
        if (dist >= kernelRadius)
        {
            return 0.0f;
        }
        
        float volume = PI * kernelRadius4 / 6;
        return (kernelRadius - dist) * (kernelRadius - dist) / volume;
    }
    
    float dF(float dist)
    {
        if (dist >= kernelRadius)
        {
            return 0;
        }

        float scale = 12 / (kernelRadius4 * PI);
        return (dist - kernelRadius) * scale;
    }
    
    float ddF(float dist)
    {
        if (dist >= kernelRadius)
        {
            return 0;
        }

        float volume = PI * kernelRadius4 * kernelRadius4 / 4;
        float x = max(0, kernelRadius2 - dist * dist);
        return x * x * x / volume;
    }
    
    float2 grad(float dist, float2 normalizedDirToCenter)
    {
        return dF(dist) * normalizedDirToCenter;
    }
};

Spiky SpikyParticleKernel;

/*
    ################################
    ############ UTIL ##############
    ################################
*/

float2 rand(float2 p)
{
    float3 p3 = frac(float3(p.xyx) * float3(.1031, .1030, .0973));
    p3 += dot(p3, p3.yzx + 33.33);
    return frac((p3.xx + p3.yz) * p3.zy);
}

float2 transform(float2 x)
{
    return (x + offset) * scale;
}

float magnitude2(float2 a)
{
    return dot(a, a);
}

/*
    ################################
    ############# SIM ##############
    ################################
*/

void resolveCollisions(uint i)
{
    float halfBound = 0.5f - particleRadius;
    float2 pos = positions[i];
    float2 vel = velocities[i];
    
    if (abs(pos.x) > halfBound)
    {
        pos.x = halfBound * sign(pos.x);
        vel.x *= -1 * restitutionCoeff;
    }
    if (abs(pos.y) > halfBound)
    {
        pos.y = halfBound * sign(pos.y);
        vel.y *= -1 * restitutionCoeff;
    }
 
    positions[i] = pos;
    velocities[i] = vel;
}

float sampleKernelAt(float2 pos)
{
    float sum = 0.0f;
    
    for (int i = 0; i < numParticles; i++)
    {
        sum += SpikyParticleKernel.F(distance(pos, predictedPositions[i]));
    }
    
    return sum;
}

void computeDensities(uint i)
{
    densities[i] = particleMass * sampleKernelAt(predictedPositions[i]);
    InterlockedMax(stats[0], (int) (densities[i] * 1000));
}

float getPressureFromDensity(float density)
{
    float diff = density - targetDensity;
    return pressureCoeff * diff;
}

float getPressureFromDensity(float density1, float density2)
{
    float diff1 = density1 - targetDensity;
    float diff2 = density2 - targetDensity;
    return 0.5f * pressureCoeff * (diff1 + diff2);
}

void computePressureForce(int i)
{
    float2 pressureForce = (float2) 0;
    
    for (int j = 0; j < numParticles; j++)
    {
        if (i == j)
            continue;
        
        // Get direction and magnitude
        float len = distance(predictedPositions[j], predictedPositions[i]);
        float2 ndir = (predictedPositions[j] - predictedPositions[i]);
        if (len > 0.00001f)
            ndir /= len;
        else
            ndir = normalize(rand(float2(i, j)));

        
        float2 grad = SpikyParticleKernel.grad(len, ndir);
        float pressure = getPressureFromDensity(densities[i], densities[j]);
        
        pressureForce += pressure * grad / densities[j];
    }

    forces[i] += pressureForce * particleMass / densities[i];
}

void computeViscosityForce(int i)
{
    float2 viscosityForce = (float2) 0;
    
    for (int j = 0; j < numParticles; j++)
    {
        if (i == j)
            continue;
        
        float len = distance(predictedPositions[j], predictedPositions[i]);
        viscosityForce += (velocities[j] - velocities[i]) * SpikyParticleKernel.ddF(len);
    }

    forces[i] += viscosityCoeff * viscosityForce;
}

void interactionForce(int i)
{
    if (!pointerActive)
        return;
    
    float dist = distance(positions[i], pointerPos);
    if (dist > pointerRadius)
        return;
    
    float2 dir = (float2) 0;
    if (dist > 0.0001f)
    {
        dir = (pointerPos - positions[i]) / dist;
    }
    
    float val = 1 - dist / pointerRadius;
    velocities[i] += (dir * pointerStrength - velocities[i]) * val * fixedDeltaTime;
}

void preStep(uint i)
{

}

/*
    ################################
    ############ KERN ##############
    ################################
*/

[numthreads(X,1,1)]
void Particle(uint3 id : SV_DispatchThreadID)
{
    uint w, h;
    result.GetDimensions(w, h);
    uint total = w * h;
    
    if (id.x >= total)
        return;
    
    uint2 coords = uint2(id.x / h, id.x % h);
    float2 ncoords = float2((float) coords.x / w, (float) coords.y / h);
    float2 tcoords = transform(ncoords);
    
    if (distance(distance(pointerPos, tcoords), pointerRadius) < 0.001f)
    {
        result[coords.xy] = float4(0, 1, 0, 1);
        return;
    }
    
    for (int i = 0; i < numParticles; i++)
    {
        if (distance(tcoords, positions[i]) < particleRadius)
        {
            float v = length(velocities[i]) * 2.0f;
            float3 color = lerp(float3(0.24, 0.35, 0.99), lerp(float3(0, 0.76, 1), lerp(float3(0, 0.9, 0.46), lerp(float3(0.96, 0.82, 0.25), float3(1, 0.34, 0.2), v), v), v), v);
            result[coords.xy] = float4(color, 1.0f);
            return;
        }
    }
}

[numthreads(X, 1, 1)]
void Density(uint3 id : SV_DispatchThreadID)
{
    uint w, h;
    result.GetDimensions(w, h);
    uint total = w * h;
    
    if (id.x >= total)
        return;
    
    uint2 coords = uint2(id.x / h, id.x % h);
    float2 ncoords = float2((float) coords.x / w, (float) coords.y / h);
    float2 tcoords = transform(ncoords);
    
    float density = particleMass * sampleKernelAt(tcoords);
    InterlockedMax(stats[0], (int) (density * 1000));
    
    result[coords.xy] = float4(density, density, 0.0f, 1.0f);
}

[numthreads(X, 1, 1)]
void Pressure(uint3 id : SV_DispatchThreadID)
{
    uint w, h;
    result.GetDimensions(w, h);
    uint total = w * h;
    
    if (id.x >= total)
        return;
    
    uint2 coords = uint2(id.x / h, id.x % h);
    float2 ncoords = float2((float) coords.x / w, (float) coords.y / h);
    float2 tcoords = transform(ncoords);
    
    float density = particleMass * sampleKernelAt(tcoords);
    float pressure = getPressureFromDensity(density);
    
    InterlockedMin(stats[1], (int) (pressure * 1000));
    InterlockedMax(stats[2], (int) (pressure * 1000));
    
    
    float4 neg = float4(1.0f, 0.0f, 0.0f, 1.0f);
    float4 zero = float4(1.0f, 1.0f, 1.0f, 1.0f);
    float4 pos = float4(0.0f, 0.0f, 1.0f, 1.0f);
    
    result[coords.xy] = pressure < 0.0f ? lerp(zero, neg, -pressure * 0.1f) : lerp(zero, pos, pressure * 0.1f);
}


[numthreads(X, 1, 1)]
void RandomInit(uint3 id : SV_DispatchThreadID)
{
    uint x, _;
    positions.GetDimensions(x, _);

    if (id.x >= x)
        return;
    
    positions[id.x] = transform(rand(id.xx));
    velocities[id.x] = (float2)0;
    forces[id.x] = (float2)0;
}

[numthreads(X, 1, 1)]
void PreStep(uint3 id : SV_DispatchThreadID)
{
    uint x, _;
    positions.GetDimensions(x, _);

    if (id.x >= x)
        return;
    
    // Predict
    float2 prevPos = positions[id.x];
    velocities[id.x] += float2(0, gravityCoeff) * fixedDeltaTime;
    predictedPositions[id.x] += velocities[id.x] * fixedDeltaTime;
    
    // Reset forces
    forces[id.x] = 0.0f;
    
    
    // Update index
    
    // Recalculate neighbors
    
}

[numthreads(X, 1, 1)]
void Step(uint3 id : SV_DispatchThreadID)
{
    uint x, _;
    positions.GetDimensions(x, _);

    if (id.x >= x)
        return;
    
    // Compute densities
    computeDensities(id.x);
    
    // Calculate forces
    computePressureForce(id.x);
    computeViscosityForce(id.x);
    
    // Misc
    interactionForce(id.x);
    
    // Integration
    velocities[id.x] += forces[id.x] * fixedDeltaTime;
    positions[id.x] += velocities[id.x] * fixedDeltaTime;
    
    
    // Recolving collisions
    resolveCollisions(id.x);
}