#pragma kernel Clear
#pragma kernel Initialize

#include "ComputeGrid.hlsl"

//#define DEBUG

uint numPoints;
RWStructuredBuffer<float3> points;

#ifdef DEBUG
    RWStructuredBuffer<uint> debug;
#endif

void insert(float3 pos, uint value)
{
    uint bucketSeed = _getBucketSeed(pos);
    
    uint startIndex, endIndex;
    uint step = 0;
    uint insertIndex;
    
    while (true)
    {
        _getBucketRange(bucketSeed, step++, startIndex, endIndex);
        InterlockedAdd(IndexGrid[startIndex + _bucketCapacity - 1], 1, insertIndex);
        
        if (insertIndex < _bucketCapacity - 1)
        {
            IndexGrid[startIndex + insertIndex] = value;
            break;
        }
    }
}

// TODO: Clear only on positions (before predict step aka before positions change) 
//  -> Cannot do since some bucket will clear step 1+ buckets and break cleanup of others
[numthreads(1024,1,1)]
void Clear (uint3 id : SV_DispatchThreadID)
{
    uint numBuckets = _gridSize3;
    
    if (id.x >= numBuckets)
        return;
    
    uint bucketStart = id.x * _bucketCapacity;
    uint bucketCountIndex = bucketStart + _bucketCapacity - 1;
    
#ifdef DEBUG
    InterlockedAdd(debug[0], IndexGrid[bucketCountIndex]);
    InterlockedMax(debug[1], IndexGrid[bucketCountIndex]);
#endif
    
    IndexGrid[bucketCountIndex] = 0;
}

[numthreads(1024,1,1)]
void Initialize(uint3 id : SV_DispatchThreadID)
{
    if (id.x >= numPoints)
        return;
    
    insert(points[id.x], id.x);
}