#pragma kernel Clear
#pragma kernel PrimitivesDist
#pragma kernel MeshDist

#include "ComputeSdf.hlsl"
#include "../../Collider/Compute/ColliderUtils.hlsl"

// Scale is separate from matrices for easier
//  calculations with bodies that have radius
struct BoxInfo
{
    float4x4 inverseTR;
    float4x4 TR;
    float4 scale; // Scale 1-3 | RigidBodyIndex 4
};

uint numSpheres;
uint numBoxes;
float margin;

RWStructuredBuffer<BoxInfo> Boxes;
RWStructuredBuffer<float4> Spheres;

uint numIndices;
RWStructuredBuffer<float3> MeshVertices;
RWStructuredBuffer<float3> MeshNormals;
RWStructuredBuffer<uint> MeshIndices;

/*
##################################################################
########################  HELPER  ################################
##################################################################
*/

float dot2(in float3 v)
{
    return dot(v, v);
}

/*
    Unsigned Distance to triangle
    https://iquilezles.org/articles/triangledistance/
*/
float udTriangle(in float3 v1, in float3 v2, in float3 v3, in float3 p)
{
    // prepare data    
    float3 v21 = v2 - v1;
    float3 p1 = p - v1;
    float3 v32 = v3 - v2;
    float3 p2 = p - v2;
    float3 v13 = v1 - v3;
    float3 p3 = p - v3;
    float3 nor = cross(v21, v13);

    return sqrt
    (   
        // inside/outside test    
        (sign(dot(cross(v21, nor), p1)) +
        sign(dot(cross(v32, nor), p2)) +
        sign(dot(cross(v13, nor), p3)) < 2.0)
        ?
        // 3 edges    
        min(min(
        dot2(v21 * clamp(dot(v21, p1) / dot2(v21), 0.0, 1.0) - p1),
        dot2(v32 * clamp(dot(v32, p2) / dot2(v32), 0.0, 1.0) - p2)),
        dot2(v13 * clamp(dot(v13, p3) / dot2(v13), 0.0, 1.0) - p3))
        :
        // 1 face    
        dot(nor, p1) * dot(nor, p1) / dot2(nor)
    );
}

float3 interpolateNormal(in float3 p, in float3 v0, in float3 v1, in float3 v2, in float3 n0, in float3 n1, in float3 n2)
{
    // Compute the edges
    float3 edge0 = v1 - v0;
    float3 edge1 = v2 - v0;
    float3 edge2 = p - v0;

    // Compute area of the full triangle using cross product
    float area = length(cross(edge0, edge1));

    // Compute barycentric coordinates
    float u = length(cross(edge2, edge1)) / area;
    float v = length(cross(edge0, edge2)) / area;
    float w = 1.0 - u - v; // Ensure weights sum to 1

    // Interpolate the normal using barycentric coordinates
    return normalize(n0 * w + n1 * u + n2 * v);
}

float3 getTriangleNormal(in float3 v0, in float3 v1, in float3 v2)
{
    return normalize(cross(v1 - v0, v2 - v0));
}

/*
##################################################################
####################  DISTANCE FUNCS  ############################
##################################################################
*/

void calculateSphere(int i, uint3 coords)
{
    FieldVal fieldVal = Field[coords];
    
    // Retrieve sphere data
    float3 spherePos = Spheres[i].xyz;
    float radius = Spheres[i].w;
    
#ifdef ENABLE_SDF_MARGIN
    radius += margin;
#endif

    // Convert voxel coordinates to world space
    float3 worldPos = lerp(_sdfBoundsMin, _sdfBoundsMax, (float3(coords) + 0.5f) / _sdfResolution);
    
    float dist = distance(worldPos, spherePos);
    float signedDistance = dist - radius;
    
#ifdef ENABLE_SDF_NORMAL
    if (signedDistance < fieldVal.r)
    {
        float3 normal = normalize(worldPos - spherePos);
        float3 spherePoint = spherePos + normal * radius;
        fieldVal.gba = spherePoint - worldPos;
    }
#endif
    
    fieldVal.r = min(fieldVal.r, signedDistance);
    Field[coords.xyz] = fieldVal;
}

void calculateBox(int i, uint3 coords)
{
    FieldVal fieldVal = Field[coords.xyz];
    
    // Convert voxel coordinates to world space
    float3 worldPos = lerp(_sdfBoundsMin, _sdfBoundsMax, (float3(coords) + 0.5f) / _sdfResolution);

    // Transform the world position into local space using the inverse of the box's transformation matrix
    float3 localPos = mul(Boxes[i].inverseTR, float4(worldPos, 1.0)).xyz;

    float3 halfScale = Boxes[i].scale.xyz / 2.0f;

#ifdef ENABLE_SDF_MARGIN
    halfScale += margin;
#endif
    
    float signedDistance = sdBox(localPos, halfScale);
    
#ifdef ENABLE_SDF_NORMAL
    if (signedDistance < fieldVal.r)
    {
        float3 closestPointLocal = closestPointBoxSurface(localPos, halfScale);
        float3 closestPointWorld = mul(Boxes[i].TR, float4(closestPointLocal, 1.0f)).xyz;
        fieldVal.gba = closestPointWorld - worldPos;
    }
#endif

    fieldVal.r = min(fieldVal.r, signedDistance);
    Field[coords.xyz] = fieldVal;
}

void calculateMesh(uint3 coords)
{
    FieldVal fieldVal = Field[coords.xyz];
    
    // Convert voxel coordinates to world space
    float3 worldPos = lerp(_sdfBoundsMin, _sdfBoundsMax, (float3(coords) + 0.5f) / _sdfResolution);

    float minDistance = 1e6;
    bool isInside = false;
    float3 normal = (float3) 0;

    for (uint i = 0; i < numIndices; i += 3)
    {
        float3 a = MeshVertices[MeshIndices[i]];
        float3 b = MeshVertices[MeshIndices[i + 1]];
        float3 c = MeshVertices[MeshIndices[i + 2]];
        
        float3 an = MeshNormals[MeshIndices[i]];
        float3 bn = MeshNormals[MeshIndices[i + 1]];
        float3 cn = MeshNormals[MeshIndices[i + 2]];
        
#ifdef ENABLE_SDF_MARGIN
        a += an * margin;
        b += bn * margin;
        c += cn * margin;
#endif
        
        float3 closestPoint = closestPointTriangle(worldPos, a, b, c);
        float distanceToTriangle = distance(closestPoint, worldPos);
        
        if (distanceToTriangle < minDistance)
        {
            minDistance = distanceToTriangle;
            float3 closestPointNormal = interpolateNormal(closestPoint, a, b, c, an, bn, cn);
            isInside = dot(closestPointNormal, (worldPos - closestPoint)) <= 0.0f; // SD to triangle plane
            normal = closestPoint - worldPos;
        }
    }
    
    float signedDistance = minDistance * (isInside ? -1 : 1);
    
#ifdef ENABLE_SDF_NORMAL
    if (signedDistance < fieldVal.r)
    {
        fieldVal.gba = normal;
    }
#endif
    
    fieldVal.r = min(fieldVal.r, signedDistance);
    Field[coords.xyz] = fieldVal;
}

/*
##################################################################
########################  KERNEL  ################################
##################################################################
*/

[numthreads(8, 8, 8)]
void Clear(uint3 id : SV_DispatchThreadID)
{
    if (id.x >= _sdfResolution || id.y >= _sdfResolution || id.z >= _sdfResolution)
        return;
    
    FieldVal val = Field[id.xyz];
    val.r = 1e6;
    
#ifdef ENABLE_SDF_NORMAL
    val.gba = (float3) 0;
#endif
    
    Field[id.xyz] = val;
}

[numthreads(8,8,8)]
void PrimitivesDist(uint3 id : SV_DispatchThreadID)
{
    if (id.x >= _sdfResolution || id.y >= _sdfResolution || id.z >= _sdfResolution)
        return;
    
    for (uint i = 0; i < numSpheres; i++)
    {
        calculateSphere(i, id);
    }

    for (uint j = 0; j < numBoxes; j++)
    {
        calculateBox(j, id);
    }

}

[numthreads(8, 8, 8)]
void MeshDist(uint3 id : SV_DispatchThreadID)
{
    if (id.x >= _sdfResolution || id.y >= _sdfResolution || id.z >= _sdfResolution)
        return;
    
    calculateMesh(id);
}