#pragma kernel Predict
#pragma kernel Density
#pragma kernel Pressure
#pragma kernel Viscosity
#pragma kernel Step

#pragma multi_compile DISABLE_3D ENABLE_3D

#define X 1024
#define PI 3.14159265359f

// Just in case
#if defined(DISABLE_3D) && defined(ENABLE_3D)
#   error "Cannot enable both macros!"
#endif

// Define dimension
#ifdef DISABLE_3D
#   define vec float2
#elif defined(ENABLE_3D) 
#   define vec float3
#endif

// Remove intellisense errors
#ifndef vec
#   define vec float2
#endif

/*
    ################################
    ########### STRUCTS ############
    ################################
*/



/*
    ################################
    ############ DATA ##############
    ################################
*/

bool pointerActive = 0;
float pointerRadius = 0.3f;
float pointerStrength = 1.0f;
float3 pointerPos;

int numParticles;
float particleRadius;
float particleMass;
float restitutionCoeff;
float targetDensity; 
float pressureCoeff;
float nearPressureCoeff;
float viscosityCoeff;
float gravityCoeff;
float kernelRadius;
float kernelRadius2;
float kernelRadius3;
float kernelRadius4;
float kernelRadius5;

float4x4 trMat;
float4x4 trMatInv;
float3 scale;

RWStructuredBuffer<vec> positions;
RWStructuredBuffer<vec> velocities;
RWStructuredBuffer<vec> forces;
RWStructuredBuffer<float> densities;

RWTexture2D<float4> result;

RWStructuredBuffer<int> stats; 

float timeStep;

/*
    ################################
    ###### PARTICLE KERNELS ########
    ################################
*/

struct Spiky
{
    float F(float dist)
    {
        if (dist >= kernelRadius)
        {
            return 0.0f;
        }
        
        float x = 1.0f - dist / kernelRadius;
        return 15.0f / (PI * kernelRadius3) * x * x * x;
    }
    
    float dF(float dist)
    {
        if (dist >= kernelRadius)
        {
            return 0;
        }

        float x = 1.0f - dist / kernelRadius;
        return -45.0f / (PI * kernelRadius4) * x * x;
    }
    
    float ddF(float dist)
    {
        if (dist >= kernelRadius)
        {
            return 0;
        }

        float x = 1.0f - dist / kernelRadius;
        return 90.0f / (PI * kernelRadius5) * x;
    }
    
    vec grad(float dist, vec normalizedDirToCenter)
    {
        return -dF(dist) * normalizedDirToCenter;
    }
};

Spiky SpikyParticleKernel;
 
/*
    ################################
    ############ UTIL ##############
    ################################
*/

float3 rand(float3 p3)
{
    p3 = frac(p3 * float3(.1031, .1030, .0973));
    p3 += dot(p3, p3.yxz + 33.33);
    return frac((p3.xxy + p3.yxx) * p3.zyx);

}

float magnitude2(vec a)
{
    return dot(a, a);
}

float3 to_float3(float2 val)
{
    return float3(val, 0.0f);
}

float3 to_float3(float3 val)
{
    return val;
}

/*
    ################################
    ############# SIM ##############
    ################################
*/

void resolveCollisions(uint i)
{
    float3 halfBound = float3(.5f, .5f, .5f) * scale - particleRadius;
    
    float3 pos = to_float3(positions[i]);
    float3 local_pos = mul(trMatInv, float4(pos, 1.0f)).xyz;
    float3 vel = to_float3(velocities[i]);
    float3 local_vel = mul((float3x3) trMatInv, vel);

    if (abs(local_pos.x) > halfBound.x)
    {
        local_pos.x = halfBound.x * sign(local_pos.x);
        local_vel.x *= -1 * restitutionCoeff;
    }
    if (abs(local_pos.y) > halfBound.y)
    {
        local_pos.y = halfBound.y * sign(local_pos.y);
        local_vel.y *= -1 * restitutionCoeff;
    }
    if (abs(local_pos.z) > halfBound.z)
    {
        local_pos.z = halfBound.z * sign(local_pos.z);
        local_vel.z *= -1 * restitutionCoeff;
    }
    
    positions[i] = mul(trMat, float4(local_pos, 1.0f));
    velocities[i] = mul((float3x3) trMat, local_vel);
}

float sampleKernelAt(vec pos)
{
    float sum = 0.0f;
    
    for (int i = 0; i < numParticles; i++)
    {
        sum += SpikyParticleKernel.F(distance(pos, positions[i]));
    }
    
    return sum;
}

void computeDensities(uint i)
{
    densities[i] = particleMass * sampleKernelAt(positions[i]);
    InterlockedMax(stats[0], (int) (densities[i] * 1000));
}

float getPressureFromDensity(float density)
{
    float diff = density - targetDensity;
    return pressureCoeff * diff;
}

float getPressureFromDensity(float density1, float density2)
{
    float diff1 = density1 - targetDensity;
    float diff2 = density2 - targetDensity;
    return 0.5f * pressureCoeff * (diff1 + diff2);
}

void computePressureForce(int i)
{
    vec pressureForce = (vec) 0;
    
    for (int j = 0; j < numParticles; j++)
    {
        if (i == j)
            continue;
        
        float len = distance(positions[j], positions[i]);
        
        vec ndir = (positions[j] - positions[i]);
        
        if (len > 0.0f)
            ndir /= len;
        else
            ndir = normalize(rand(float3(i, j, 0)));

        vec grad = SpikyParticleKernel.grad(len, ndir);
        float pressure = -getPressureFromDensity(densities[i], densities[j]);
        
        pressureForce += pressure * grad / densities[j];
    }

    forces[i] += pressureForce * particleMass / densities[i];
}

void computeViscosityForce(int i)
{
    vec viscosityForce = (vec) 0;
    
    for (int j = 0; j < numParticles; j++)
    {
        if (i == j)
            continue;
        
        float len = distance(positions[j], positions[i]);
        viscosityForce += (velocities[j] - velocities[i]) * SpikyParticleKernel.ddF(len) / densities[j];
    }

    forces[i] += particleMass * particleMass * viscosityCoeff * viscosityForce / densities[i];
}

void interactionForce(int i)
{
    if (!pointerActive)
        return;
    
    float dist = distance(positions[i], pointerPos);
    if (dist > pointerRadius)
        return;
    
    vec dir = (vec) 0;
    if (dist > 0.0001f)
    {
        dir = (pointerPos - positions[i]) / dist;
    }
    
    float val = 1 - dist / pointerRadius;
    forces[i] += (dir * pointerStrength - velocities[i]) * val;
}

void computeExternalForce(int i)
{
    forces[i] += float3(0.0f, gravityCoeff, 0.0f);

    interactionForce(i);
}

/*
    ################################
    ############ KERN ##############
    ################################
*/



[numthreads(X, 1, 1)]
void Predict(uint3 id : SV_DispatchThreadID)
{
    uint x, _;
    positions.GetDimensions(x, _);

    if (id.x >= x)
        return;
    
    // Update index
    
    // Recalculate neighbors
    
    // Reset forces
    forces[id.x] = (vec) 0.0f;
    
    // External forces
    computeExternalForce(id.x);
}

[numthreads(X, 1, 1)]
void Density(uint3 id : SV_DispatchThreadID)
{
    uint x, _;
    positions.GetDimensions(x, _);

    if (id.x >= x)
        return;
    
    // Compute densities
    computeDensities(id.x);
}

[numthreads(X, 1, 1)]
void Pressure(uint3 id : SV_DispatchThreadID)
{
    uint x, _;
    positions.GetDimensions(x, _);

    if (id.x >= x)
        return;
    
    computePressureForce(id.x);
}

[numthreads(X, 1, 1)]
void Viscosity(uint3 id : SV_DispatchThreadID)
{
    uint x, _;
    positions.GetDimensions(x, _);

    if (id.x >= x)
        return;
    
    computeViscosityForce(id.x);
}

[numthreads(X, 1, 1)]
void Step(uint3 id : SV_DispatchThreadID)
{
    velocities[id.x] += forces[id.x] * timeStep;
    positions[id.x] += velocities[id.x] * timeStep;
    
    resolveCollisions(id.x);
}