#pragma kernel Predict
#pragma kernel Density
#pragma kernel Pressure
#pragma kernel Viscosity
#pragma kernel Step

#pragma multi_compile DISABLE_3D ENABLE_3D

#include "../../SDF/Compute/ComputeSdf.hlsl"

#define X 1024

// Just in case
#if defined(DISABLE_3D) && defined(ENABLE_3D)
#   error "Cannot enable both macros!"
#endif

// Define dimension
#ifdef DISABLE_3D
#   define vec float2
#   include "FluidMaths2D.hlsl"
#elif defined(ENABLE_3D) 
#   define vec float3
#   include "FluidMaths3D.hlsl"
#endif

// Remove intellisense errors
#ifndef vec
#   define vec float2
#   include "FluidMaths2D.hlsl"
#endif


/*
    ################################
    ############ DATA ##############
    ################################
*/

bool pointerActive = 0;
float pointerRadius = 0.3f;
float pointerStrength = 1.0f;
float3 pointerPos;

int numParticles;
float particleRadius;
float particleMass;
float restitutionCoeff;
float targetDensity;
float pressureCoeff;
float nearPressureCoef;
float viscosityCoeff;
float gravityCoeff;
float kernelRadius;
float kernelRadius2;
float kernelRadius3;
float kernelRadius4;
float kernelRadius5;

float4x4 trMat;
float4x4 trMatInv;
float3 scale;

RWStructuredBuffer<vec> positions;
RWStructuredBuffer<vec> predictedPositions;
RWStructuredBuffer<vec> velocities;
RWStructuredBuffer<vec> forces;
RWStructuredBuffer<float2> densities;

RWStructuredBuffer<int> stats;

float timeStep;

/*
    ################################
    ############ UTIL ##############
    ################################
*/

float3 rand(float3 p3)
{
    p3 = frac(p3 * float3(.1031, .1030, .0973));
    p3 += dot(p3, p3.yxz + 33.33);
    return frac((p3.xxy + p3.yxx) * p3.zyx);

}

float magnitude2(vec a)
{
    return dot(a, a);
}

float3 to_float3(float2 val)
{
    return float3(val, 0.0f);
}

float3 to_float3(float3 val)
{
    return val;
}

/*
    ################################
    ############# SIM ##############
    ################################
*/

void resolveSdfCollisions(uint i)
{
    FieldVal val = GET_SDF_VALUE(to_float3(positions[i]));
    if (val.r < particleRadius)
    {
        velocities[i] = restitutionCoeff * reflect(velocities[i], val.gba);
        
        // Pushes particle outside, including radius, causes jittering (You can bake margin inside SDF for better result)
        // positions[i] += normalize(val.gba) * (particleRadius - val.r) * (val.r <= 0.0f ? 1 : -1);
        positions[i] += val.gba;
    }
}

void resolveCollisions(uint i)
{
    float3 halfBound = float3(.5f, .5f, .5f) * scale - particleRadius;
    
    float3 pos = to_float3(positions[i]);
    float3 local_pos = mul(trMatInv, float4(pos, 1.0f)).xyz;
    float3 vel = to_float3(velocities[i]);
    float3 local_vel = mul((float3x3) trMatInv, vel);

    if (abs(local_pos.x) > halfBound.x)
    {
        local_pos.x = halfBound.x * sign(local_pos.x);
        local_vel.x *= -1 * restitutionCoeff;
    }
    if (abs(local_pos.y) > halfBound.y)
    {
        local_pos.y = halfBound.y * sign(local_pos.y);
        local_vel.y *= -1 * restitutionCoeff;
    }
    if (abs(local_pos.z) > halfBound.z)
    {
        local_pos.z = halfBound.z * sign(local_pos.z);
        local_vel.z *= -1 * restitutionCoeff;
    }
    
    positions[i] = mul(trMat, float4(local_pos, 1.0f));
    velocities[i] = mul((float3x3) trMat, local_vel);
}

float2 CalculateDensity(vec pos)
{
    float sqrRadius = kernelRadius2;
    float density = 0;
    float nearDensity = 0;

    for (int i = 0; i < numParticles; i++)
    {
        float sqrDist = magnitude2(predictedPositions[i] - pos);
        
        if (sqrDist > sqrRadius)
            continue;
        

        float dst = sqrt(sqrDist);
        density += FluidMaths.DensityKernel(dst, kernelRadius);
        nearDensity += FluidMaths.NearDensityKernel(dst, kernelRadius);
    }

    return float2(density, nearDensity);
}

float PressureFromDensity(float density)
{
    return (density - targetDensity) * pressureCoeff;
}

float NearPressureFromDensity(float nearDensity)
{
    return nearPressureCoef * nearDensity;
}

/*
    ################################
    ############ KERN ##############
    ################################
*/

[numthreads(X, 1, 1)]
void Predict(uint3 id : SV_DispatchThreadID)
{
    uint x, _;
    positions.GetDimensions(x, _);

    if (id.x >= x)
        return;
    
    // EXTERNAL
    
    float3 gravity = float3(0, gravityCoeff, 0);
    
    //if (pointerActive)
    //{
    //    float2 inputPointOffset = pointerPos - positions[id.x];
    //    float sqrDst = dot(inputPointOffset, inputPointOffset);
    //    if (sqrDst < interactionInputRadius * interactionInputRadius)
    //    {
    //        float dst = sqrt(sqrDst);
    //        float edgeT = (dst / interactionInputRadius);
    //        float centreT = 1 - edgeT;
    //        float2 dirToCentre = inputPointOffset / dst;

    //        float gravityWeight = 1 - (centreT * saturate(interactionInputStrength / 10));
    //        float2 accel = gravityAccel * gravityWeight + dirToCentre * centreT * interactionInputStrength;
    //        accel -= velocity * centreT;
    //        return accel;
    //    }
    //}
    
    velocities[id.x] += gravity * timeStep;

    // PREDICT
    float predictionStep = timeStep; // TODO: Fine tune
    predictedPositions[id.x] = positions[id.x] + velocities[id.x] * predictionStep;
}

[numthreads(X, 1, 1)]
void Density(uint3 id : SV_DispatchThreadID)
{
    uint x, _;
    positions.GetDimensions(x, _);

    if (id.x >= x)
        return;

    densities[id.x] = CalculateDensity(predictedPositions[id.x]);
}

[numthreads(X, 1, 1)]
void Pressure(uint3 id : SV_DispatchThreadID)
{
    uint x, _;
    positions.GetDimensions(x, _);

    if (id.x >= x)
        return;

    float density = densities[id.x][0];
    float densityNear = densities[id.x][1];
    float pressure = PressureFromDensity(density);
    float nearPressure = NearPressureFromDensity(densityNear);
    vec pressureForce = 0;
	
    vec pos = predictedPositions[id.x];
    float sqrRadius = kernelRadius2;
    
    for (int i = 0; i < numParticles; i++)
    {
        vec offsetToNeighbour = predictedPositions[i] - pos;
        float sqrDist = magnitude2(offsetToNeighbour);
        
        if (sqrDist > sqrRadius || i == id.x)
            continue;
        
        float dst = sqrt(sqrDist);
        vec dirToNeighbour = dst > 0 ? offsetToNeighbour / dst : float3(0, 1, 0);

        float neighbourDensity = densities[i][0];
        float neighbourNearDensity = densities[i][1];
        float neighbourPressure = PressureFromDensity(neighbourDensity);
        float neighbourNearPressure = NearPressureFromDensity(neighbourNearDensity);

        float sharedPressure = (pressure + neighbourPressure) * 0.5;
        float sharedNearPressure = (nearPressure + neighbourNearPressure) * 0.5;

        pressureForce += dirToNeighbour * FluidMaths.DensityDerivative(dst, kernelRadius) * sharedPressure / neighbourDensity;
        pressureForce += dirToNeighbour * FluidMaths.NearDensityDerivative(dst, kernelRadius) * sharedNearPressure / neighbourNearDensity;
    }
    
    vec acceleration = pressureForce / density;
    velocities[id.x] += acceleration * timeStep;
}

[numthreads(X, 1, 1)]
void Viscosity(uint3 id : SV_DispatchThreadID)
{
    uint x, _;
    positions.GetDimensions(x, _);

    if (id.x >= x)
        return;

    vec pos = predictedPositions[id.x];
    float sqrRadius = kernelRadius2;
    vec viscosityForce = 0;
    vec velocity = velocities[id.x];

    for (int i = 0; i < numParticles; i++)
    {
        vec offsetToNeighbour = predictedPositions[i] - pos;
        float sqrDist = magnitude2(offsetToNeighbour);
        
        if (sqrDist > sqrRadius || i == id.x)
            continue;
        
		float dst = sqrt(sqrDist);
        vec neighbourVelocity = velocities[i];
        viscosityForce += (neighbourVelocity - velocity) * FluidMaths.ViscosityKernel(dst, kernelRadius);
    }
    
	velocities[id.x] += viscosityForce * viscosityCoeff * timeStep;
}

[numthreads(X, 1, 1)]
void Step(uint3 id : SV_DispatchThreadID)
{
    uint x, _;
    positions.GetDimensions(x, _);

    if (id.x >= x)
        return;
    
    positions[id.x] += velocities[id.x] * timeStep;
    resolveSdfCollisions(id.x);
    resolveCollisions(id.x);
}